FROM rust:1.76.0-slim-bullseye as build

RUN apt update -y && apt install -y pkg-config libssl-dev

WORKDIR /src
COPY . .
WORKDIR /src/db-api
RUN apt update -y && apt upgrade -y && apt install musl-tools -y
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build -r --target x86_64-unknown-linux-musl

FROM alpine as final
EXPOSE 80
WORKDIR /app
COPY --from=build /src/target/x86_64-unknown-linux-musl//release/db-api ./db-api

ENTRYPOINT ["./db-api"]