[package]
name = "shared"
version = "0.1.0"
edition = "2021"
workspace = "../"

[dependencies]
serde = { version = "^1", features = ["derive"] }
derive_more = "^0.99"
bson = "^2"
getrandom = { version = "0.2", features = ["js"] }